
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-27T02:30:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a958c92952be416ee032b99e6d4fc6e6da8a3f2e",
 "version": "0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
